# Generated by Django 3.2 on 2021-04-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('artist', models.CharField(max_length=50)),
                ('file_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='song_fingerprint',
            fields=[
                ('id', models.IntegerField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('hash', models.CharField(db_index=True, max_length=35)),
                ('offset', models.IntegerField()),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_classification_api.song')),
            ],
        ),
    ]
