# Generated by Django 3.2 on 2021-04-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_classification_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='song_fingerprint',
            new_name='SongFingerprint',
        ),
    ]
