# Generated by Django 3.2 on 2021-05-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_classification_api', '0002_rename_song_fingerprint_songfingerprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songfingerprint',
            old_name='song_id',
            new_name='song',
        ),
    ]
