# Generated by Django 3.2 on 2021-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_classification_api', '0003_rename_song_id_songfingerprint_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='total_fingerprints',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
