# Generated by Django 3.2 on 2021-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_classification_api', '0004_song_total_fingerprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
