# Generated by Django 3.2 on 2021-06-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_classification_api', '0007_alter_songfingerprint_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='tbl_songs',
        ),
        migrations.AlterModelTable(
            name='songfingerprint',
            table='tbl_song_fingperints',
        ),
    ]
