# Generated by Django 3.2 on 2021-06-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_classification_api', '0008_auto_20210602_0415'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='songfingerprint',
            table='tbl_song_fingerpints',
        ),
    ]
