# Generated by Django 3.2 on 2021-06-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_classification_api', '0010_alter_songfingerprint_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfingerprint',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
