# Generated by Django 3.2 on 2021-06-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_classification_api', '0011_alter_songfingerprint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfingerprint',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
